apiVersion: v1
kind: Secret
metadata:
  name: phone-directory-secrets
  namespace: phone-directory
type: Opaque
data:
  # echo -n 'postgres' | base64
  DATABASE_USER: cG9zdGdyZXM=
  # echo -n 'postgres' | base64
  DATABASE_PASSWORD: cG9zdGdyZXM=