apiVersion: v1
kind: ConfigMap
metadata:
  name: phone-directory-config
  namespace: phone-directory
data:
  DATABASE_NAME: "phone_directory"
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"
  FLASK_APP: "app.py"
  FLASK_DEBUG: "false"