apiVersion: v1
kind: ConfigMap
metadata:
  name: telephone-config
  namespace: telephone
data:
  DATABASE_NAME: "phone_directory"
  DATABASE_PORT: "5432"
  FLASK_APP: "app.py"
  DATABASE_HOST: "telephone-postgres"
  FLASK_DEBUG: "false"
